name: Bug Report
description: バグ報告はこちら
title: "[Bug] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: 問題詳細
      description: 問題が発生した viMarkdown version, 期待した結果と実際には何が起きたか？
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
    validations:
      required: true
